version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: 'docker'
    depends_on:
      - db

  db:
    image: "mariadb"
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: 'testing'
      MARIADB_ROOT_PASSWORD: 'root'
      MYSQL_UNIX_PORT: 3307
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - db-data:/foo


volumes:
  db-data:

